-- Compact global rules and store four ordered chain scenes as authorable text.
-- Deploy the scene-aware backend before activating Chains.
-- Preserve modules already at v2 or later. Back up live rows before applying.
BEGIN;
UPDATE public.prompt_modules
SET prompt_text = $chain_v2$CHAINS CATEGORY RULES. Standalone neck chain is the hero. Preserve length, link shape/width/thickness/pitch, visible pattern sequence, rigid stations, strands, end fittings, connectors, visible clasp, finish and asymmetry. Never extrapolate unseen link counts. One chain stays one even if a reference shows several; two runs of a loop are not two products. Preserve real multi-strand joins and approved products; exclude incidental products/reflections.

No invented pendant, charm, central drop, bead, stone, extra strand or matching product. Preserve genuine unexpected components rather than deleting jewellery to force category conformity. Never copy reference designs/counts, substitute a generic chain, fuse links, fill openwork or turn links into a ribbon. Hidden/cropped ends or clasps must not be invented. Tag removal must preserve fine metal links and actual findings.

Pose changes only through genuine articulation: dimensions, length and component order stay fixed. Adapt support/framing, not chain length. Keep open ends open; no invented closure or compulsory deep U. Rigid stations stay rigid; joints bend plausibly. No sharp kinks, impossible twists/crossings, duplicated loops or fused strands. Top runs need real support; lower runs follow gravity or rest naturally. No adhesive-looking placement or invented hooks. Suspended sections may cast offset shadows, not fake contact outlines. Keep supported chain, ends and clasp fully readable; no crop. Preserve fine edges/openings, sharp defining links and source metal tone; coloured displays must not recolour jewellery. No reference flowers/leaves/rocks/fans/branding.

SCENE 1 — WHITE ARCHITECTURAL STEPS. Bright premium studio with two or three broad matte neutral-white stepped plinths, gently softened edges and a continuous white background. Drape the source chain across an upper landing, over a broad step edge, into a relaxed curve on the lower landing. For a closed construction use a traceable elongated loop; for open construction preserve ends in an open curve. Select span/height for the actual length and rigidity; keep the supported product complete and readable. Never reproduce the reference's multiple-chain assortment. Elevated three-quarter view reveals upper surfaces, front faces and edge transitions. Moderately directional upper-left light with controlled softness and fill; clear but restrained shadows. Shadows on a vertical face reflect real chain-to-face spacing, not a glued-on outline. Protect polished highlights. No marble veining, coloured border, text or unrelated props. Prioritize product readability over a complicated staircase.

SCENE 2 — CHARCOAL CURVED DISPLAY. Broad matte charcoal rounded support on a continuous dark neutral surface, subtly tactile rather than glossy. Place the upper chain run on the crest; lower runs follow the curved support into a relaxed elongated foreground loop, or a source-supported open curve. Use a broad radius compatible with rigid stations or flat articulated links. Keep each genuine source product readable; do not duplicate a single chain to copy the two reference products. Modestly elevated diagonal view, controlled neutral upper-left key and restrained fill. Keep fine links separated from dark surfaces without bright halos. All supported ends, clasp and lower turn remain visible and sharp. Gold remains source-accurate, not exaggerated orange. No copied thick openwork design, seller logo, loose rocks or decorative fan. The support visibly carries the chain; no suspended cylinder-like pipe or unsupported jewellery.

SCENE 3 — EMERALD VELVET ROLLS. Deep emerald/teal-green velvet with two or three broad horizontal upholstered rolls or soft ridges. Short realistic pile, subtle directional texture and tonal variation; no satin/plastic shine. Drape the source chain over the upper roll, down the contours into a relaxed lower curve resting on foreground velvet; preserve genuine open ends. Adapt roll radius/height to actual chain length and articulation. Slight pile compression at contact; do not bury fine links, fill openings with fibres, deform rigid stations or wrap cloth around metal. Near-front, slightly elevated view; softly directional upper-left light and neutral fill. Whole supported product stays in the square, sharp through the lower curve; only distant background may soften. Keep green reflection subtle, metal tone accurate. No reference flowers, purple branches, dried palm leaves or invented pendant. Velvet remains secondary to the chain.

SCENE 4 — BURGUNDY GEOMETRIC BLOCKS. Deep burgundy studio background with one primary wine/magenta block and at most one secondary block for depth. Matte/fine satin planes, subtly softened edges, restrained saturation; no fluorescent pink or glossy plastic. Top run rests on the primary block; sides descend in front into a source-compatible lower curve. Preserve open ends when applicable. Select block height/width for the actual chain length; no stretching or shortening. Hanging runs must be carried by the supported top run, not adhered to the vertical face. Front-oriented, slightly elevated camera reveals top support and modest block depth. Controlled upper-left directional key, moderate neutral fill and restrained side separation; crisp source-supported metal detail without pink recolouring. Shadows distinguish actual contact from offset projected shadows. Fit complete supported product into the square without a large empty portrait header. No second chain copied from reference, logo or typography.$chain_v2$, version = 2
WHERE module_type = 'category' AND jewellery_type = 'chain'
  AND version = 1 AND is_active = false;
UPDATE public.prompt_modules
SET prompt_text = $base_v2$JEWELINDIA UNIVERSAL JEWELLERY PHOTOGRAPHY. Subject: {item_description}. Produce ONE square 1:1 photograph per request; no collage, text or watermark. Application selects 1-4 scenes. Source controls product/count; references control styling only. Improve photography, never redesign.

Preserve source-supported geometry, proportions, quantity, components/order, metal construction/finish/colour, gemstones/size/shape/colour/settings, beads, motifs, engraving, filigree, relief, openings, texture and handcrafted asymmetry. No additions, omissions, duplication, merging, generic replacement or forced symmetry. Never guess hidden details from blurry, tagged or cropped input.

Completely remove prices, tags, labels, paper, barcodes, inventory/SKU/seller/promotional text, watermarks and non-jewellery attachments. Preserve genuine clasps/connectors and manufactured jewellery markings. Rebuild exposed background only; never invent jewellery under removed objects.

Rigid parts retain geometry; flexible parts articulate without changing dimensions. Respect support, gravity, weight, continuity and separation. No floating, penetration, clipping or impossible crossings. Contact shadows only at contact; suspended parts may cast offset shadows. Light, reflections and shadows stay coherent.

Correct exposure/noise/colour casts without fabricated detail. Preserve fine edges/openings; no halos, plastic/neon metal or fake sparkle. Keep source-accurate materials, controlled highlights, readable relief and sharp dominant jewellery. Plausible camera, breathing room and complete defining structure unless category explicitly permits cropping. No props/humans unless authorized by category/scene.

Category controls specific physics/presentation; selected scene controls environment/camera/light. Includes Chains with other categories. Neither overrides source fidelity, quantity, commercial removal, no-invention or square format. If styling conflicts, preserve source. QC: same product/components, supported detail, real physics, clean removal, readable photograph.$base_v2$, version = 2
WHERE module_type = 'base' AND is_active = true AND version = 1;
COMMIT;
