name: Sync Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to new repo
        run: |
          git remote add new https://${{ secrets.PAT }}@github.com/jwellery44-prog/ai-pipeline.git
          git push new main